### PR TITLE
Style update and 8 levels for two games

### PR DESCRIPTION
**Pull request by dweiss96**

### CODE REVIEW

**Comment by rm--** [comment]
I found some minor issues:
- Please delete the directories in `src/assets/` of the deleted games.
- Remove the obsolete `gamesWithoutEvaluation` constant and its usage.

**Comment by rm--** [comment]
Please add issue tags to the commit titles.

**Comment by dweiss96** [comment]
The folders are deleted as you can see here: https://github.com/eXa-online/lovemathe/tree/style_update/src/assets

**Comment by dweiss96** [comment]
- Remove the obsolete gamesWithoutEvaluation constant and its usage
- add issue tags to commits

Done

**Review by rm-- — APPROVED** [review]

**Pull request merged**
